### 파일명을 본인의 학번_이름_HW2.ipynb로 바꾸어 제출하십시오.
### (ex. 2020123456_권오성_HW2.ipynb)
### 제출기한: 4/24(월) 23:59
### -----------------------------------------------------

### 각 문제 아래칸에 답을 작성해주세요.
### 모든 문제에는 코드뿐만 아니라 풀이 과정(설명)까지 작성하셔야 합니다.
### 주석 처리를 활용하여 간단한 풀이 설명을 작성해주세요.
### 풀이 과정이 없거나 미흡할 경우 감점 처리됩니다.
### 지각 제출은 메일로 가능하나, 대폭 감점합니다.
### -----------------------------------------------------

## (문제)
### IMDb는 아마존의 자회사인 영화 정보 사이트로, 평점이 가장 높은 Top 250 영화를 확인할 수 있습니다.
### 해당 과제에서는 BeautifulSoup, Pandas를 이용하여 이를 시대별로 정리하고자 합니다.

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

## No. 1 (1점)
### BeautifulSoup을 이용하여 다음 url에서 제목, 연도, 평점 정보를 수집하세요.

In [2]:
# 기본세팅
url = 'https://www.imdb.com/chart/top/'
headers = {'User-Agent' : 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser', from_encoding='utf-8')

In [3]:
# 결과를 받을 빈 리스트 생성
result = []
for i in range(1,251):
    movie = soup.select('#main > div > span > div > div > div.lister > table > tbody > tr:nth-child(' + str(i) + ') > td.titleColumn > a') # 영화 이름 추출
    year = soup.select('#main > div > span > div > div > div.lister > table > tbody > tr:nth-child(' + str(i) + ') > td.titleColumn > span') # 연도 추출
    rate = soup.select('#main > div > span > div > div > div.lister > table > tbody > tr:nth-child(' + str(i) + ') > td.ratingColumn.imdbRating > strong') # 평점 추출
    for z in movie: 
        movie_2 = z.text # 영화 이름 추출 한 부분에서 text만 뽑아 저장
    for k in year:
        year_2 = k.text # 연도 추출한 부분에서 text만 뽑아 저장
    for j in rate:
        rate_2 = j.text # 평점 추출한 부분에서 text만 뽑아 저장
    result.append([movie_2, year_2, rate_2]) # 최종적으로 뽑은 내용 한 리스트에 저장

In [4]:
result # 저장한 리스트 확인

[['쇼생크 탈출', '(1994)', '9.2'],
 ['Daeboo', '(1972)', '9.2'],
 ['다크 나이트', '(2008)', '9.0'],
 ['The Godfather Part II', '(1974)', '9.0'],
 ['12명의 성난 사람들', '(1957)', '9.0'],
 ['쉰들러 리스트', '(1993)', '8.9'],
 ['반지의 제왕: 왕의 귀환', '(2003)', '8.9'],
 ['펄프 픽션', '(1994)', '8.8'],
 ['반지의 제왕: 반지 원정대', '(2001)', '8.8'],
 ['석양의 무법자', '(1966)', '8.8'],
 ['포레스트 검프', '(1994)', '8.8'],
 ['파이트 클럽', '(1999)', '8.7'],
 ['The Lord of the Rings: The Two Towers', '(2002)', '8.7'],
 ['인셉션', '(2010)', '8.7'],
 ['스타워즈 에피소드 5 - 제국의 역습', '(1980)', '8.7'],
 ['매트릭스', '(1999)', '8.7'],
 ['좋은 친구들', '(1990)', '8.7'],
 ['뻐꾸기 둥지 위로 날아간 새', '(1975)', '8.6'],
 ['세븐', '(1995)', '8.6'],
 ['멋진 인생', '(1946)', '8.6'],
 ['7인의 사무라이', '(1954)', '8.6'],
 ['양들의 침묵', '(1991)', '8.6'],
 ['라이언 일병 구하기', '(1998)', '8.6'],
 ['시티 오브 갓', '(2002)', '8.6'],
 ['인터스텔라', '(2014)', '8.6'],
 ['La vita è bella', '(1997)', '8.6'],
 ['그린 마일', '(1999)', '8.6'],
 ['Star Wars', '(1977)', '8.5'],
 ['Terminator 2: Judgment Day', '(1991)', '8.5'],
 ['빽 투 더 퓨쳐', '(1985)', '8.5'],
 ['센과 치히로의 행방불명', '(2001)', '8.5'],
 ['피아니스트', '(2002)', '8.5'],
 ['싸이코', '(1960)', '8.5'],
 ['Gisaengchung', '(2019)', '8.5'],
 ['레옹', '(1994)', '8.5'],
 ['라이온 킹', '(1994)', '8.5'],
 ['글래디에이터', '(2000)', '8.5'],
 ['아메리칸 히스토리 X', '(1998)', '8.5'],
 ['디파티드', '(2006)', '8.5'],
 ['위플래쉬', '(2014)', '8.5'],
 ['프레스티지', '(2006)', '8.5'],
 ['유주얼 서스펙트', '(1995)', '8.5'],
 ['카사블랑카', '(1942)', '8.5'],
 ['반딧불이의 묘', '(1988)', '8.5'],
 ['Seppuku', '(1962)', '8.5'],
 ['언터처블: 1%의 우정', '(2011)', '8.5'],
 ['모던 타임즈', '(1936)', '8.4'],
 ['원스 어폰 어 타임 인 더 웨스트', '(1968)', '8.4'],
 ['시네마 천국', '(1988)', '8.4'],
 ['이창', '(1954)', '8.4'],
 ['에이리언', '(1979)', '8.4'],
 ['City Lights', '(1931)', '8.4'],
 ['지옥의 묵시록', '(1979)', '8.4'],
 ['메멘토', '(2000)', '8.4'],
 ['장고: 분노의 추적자', '(2012)', '8.4'],
 ['레이더스', '(1981)', '8.4'],
 ['월-E', '(2008)', '8.4'],
 ['타인의 삶', '(2006)', '8.4'],
 ['Sunset Blvd.', '(1950)', '8.4'],
 ['Paths of Glory', '(1957)', '8.4'],
 ['샤이닝', '(1980)', '8.4'],
 ['The Great Dictator', '(1940)', '8.4'],
 ['어벤져스: 인피니티 워', '(2018)', '8.4'],
 ['Witness for the Prosecution', '(1957)', '8.4'],
 ['Aliens', '(1986)', '8.3'],
 ['스파이더맨: 뉴 유니버스', '(2018)', '8.3'],
 ['아메리칸 뷰티', '(1999)', '8.3'],
 ['Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
  '(1964)',
  '8.3'],
 ['Dakeu naiteu raijeu', '(2012)', '8.3'],
 ['Oldeuboi', '(2003)', '8.3'],
 ['바스터즈: 거친 녀석들', '(2009)', '8.3'],
 ['아마데우스', '(1984)', '8.3'],
 ['코코', '(2017)', '8.3'],
 ['Toy Story', '(1995)', '8.3'],
 ['Braveheart', '(1995)', '8.3'],
 ['조커', '(2019)', '8.3'],
 ['The Boat', '(1981)', '8.3'],
 ['어벤져스: 엔드게임', '(2019)', '8.3'],
 ['Mononoke-hime', '(1997)', '8.3'],
 ['원스 어폰 어 타임 인 아메리카', '(1984)', '8.3'],
 ['굿 윌 헌팅', '(1997)', '8.3'],
 ['Neoui Ileum-eun.', '(2016)', '8.3'],
 ['사랑은 비를 타고', '(1952)', '8.3'],
 ['세 얼간이', '(2009)', '8.3'],
 ['레퀴엠', '(2000)', '8.3'],
 ['천국과 지옥', '(1963)', '8.3'],
 ['토이 스토리 3', '(2010)', '8.3'],
 ['가버나움', '(2018)', '8.3'],
 ['Star Wars: Episode VI - Return of the Jedi', '(1983)', '8.3'],
 ['2001: A Space Odyssey', '(1968)', '8.3'],
 ['이터널 선샤인', '(2004)', '8.3'],
 ['컴 앤 씨', '(1985)', '8.3'],
 ['저수지의 개들', '(1992)', '8.3'],
 ['더 헌트', '(2012)', '8.3'],
 ['시민 케인', '(1941)', '8.2'],
 ['Lawrence of Arabia', '(1962)', '8.2'],
 ['M - Eine Stadt sucht einen Mörder', '(1931)', '8.2'],
 ['이키루', '(1952)', '8.2'],
 ['Bugbugseolo Jinloleul Dollyeola', '(1959)', '8.2'],
 ['Hyeongijeung', '(1958)', '8.2'],
 ['The Apartment', '(1960)', '8.2'],
 ['아멜리에', '(2001)', '8.2'],
 ['Double Indemnity', '(1944)', '8.2'],
 ['시계태엽 오렌지', '(1971)', '8.2'],
 ['Metal jaket', '(1987)', '8.2'],
 ['스카페이스', '(1983)', '8.2'],
 ['Hamilton', '(2020)', '8.2'],
 ['그을린 사랑', '(2010)', '8.2'],
 ['히트', '(1995)', '8.2'],
 ['To Kill a Mockingbird', '(1962)', '8.2'],
 ['업', '(2009)', '8.2'],
 ['The Sting', '(1973)', '8.2'],
 ['Jodaeiye Nader az Simin', '(2011)', '8.2'],
 ['Metropolis', '(1927)', '8.2'],
 ['L.A. Confidential', '(1997)', '8.2'],
 ['Taxi Driver', '(1976)', '8.2'],
 ['다이 하드', '(1988)', '8.2'],
 ['Indiana Jones and the Last Crusade', '(1989)', '8.2'],
 ['Snatch', '(2000)', '8.2'],
 ['Bicycle Thieves', '(1948)', '8.2'],
 ['Like Stars on Earth', '(2007)', '8.2'],
 ['1917', '(2019)', '8.2'],
 ['탑건: 매버릭', '(2022)', '8.2'],
 ['Downfall', '(2004)', '8.2'],
 ['Dangal', '(2016)', '8.2'],
 ['For a Few Dollars More', '(1965)', '8.2'],
 ['배트맨 비긴즈', '(2005)', '8.2'],
 ['The Kid', '(1921)', '8.2'],
 ['Some Like It Hot', '(1959)', '8.2'],
 ['더 파더', '(2020)', '8.2'],
 ['Eveeui Modeun Gut', '(1950)', '8.2'],
 ['더 울프 오브 월 스트리트', '(2013)', '8.2'],
 ['그린 북', '(2018)', '8.2'],
 ['뉘른베르크의 재판', '(1961)', '8.2'],
 ['Ran', '(1985)', '8.2'],
 ['카지노', '(1995)', '8.2'],
 ['트루먼 쇼', '(1998)', '8.2'],
 ['데어 윌 비 블러드', '(2007)', '8.2'],
 ['판의 미로 - 오필리아와 세 개의 열쇠', '(2006)', '8.2'],
 ['Unforgiven', '(1992)', '8.2'],
 ['식스 센스', '(1999)', '8.2'],
 ['셔터 아일랜드', '(2010)', '8.2'],
 ['A Beautiful Mind', '(2001)', '8.2'],
 ['Jyuragi gongwon', '(1993)', '8.2'],
 ['Yôjinbô', '(1961)', '8.1'],
 ['The Treasure of the Sierra Madre', '(1948)', '8.1'],
 ['Monty Python and the Holy Grail', '(1975)', '8.1'],
 ['노인을 위한 나라는 없다', '(2007)', '8.1'],
 ['킬 빌', '(2003)', '8.1'],
 ['The Great Escape', '(1963)', '8.1'],
 ['라쇼몽', '(1950)', '8.1'],
 ['The Thing', '(1982)', '8.1'],
 ['스파이더맨: 노 웨이 홈', '(2021)', '8.1'],
 ['Finding Nemo', '(2003)', '8.1'],
 ['The Elephant Man', '(1980)', '8.1'],
 ['Chinatown', '(1974)', '8.1'],
 ['Raging Bull', '(1980)', '8.1'],
 ['브이 포 벤데타', '(2005)', '8.1'],
 ['바람과 함께 사라지다', '(1939)', '8.1'],
 ['Lock, Stock and Two Smoking Barrels', '(1998)', '8.1'],
 ['Dial M for Murder', '(1954)', '8.1'],
 ['인사이드 아웃', '(2015)', '8.1'],
 ['Howlui umjikineun seong', '(2004)', '8.1'],
 ['El Sikeuleto: Bimil-ui Nundongja', '(2009)', '8.1'],
 ['쓰리 빌보드', '(2017)', '8.1'],
 ['Trainspotting', '(1996)', '8.1'],
 ['The Bridge on the River Kwai', '(1957)', '8.1'],
 ['프리즈너스', '(2013)', '8.1'],
 ['파고', '(1996)', '8.1'],
 ['Warrior', '(2011)', '8.1'],
 ['그랜 토리노', '(2008)', '8.1'],
 ['캐치 미 이프 유 캔', '(2002)', '8.1'],
 ['Tonari no Totoro', '(1988)', '8.1'],
 ['John Wick: Chapter 4', '(2023)', '8.1'],
 ['밀리언 달러 베이비', '(2004)', '8.1'],
 ['Children of Heaven', '(1997)', '8.1'],
 ['블레이드 러너', '(1982)', '8.1'],
 ['The Gold Rush', '(1925)', '8.1'],
 ['클라우스', '(2019)', '8.1'],
 ['Haeri Poteowa jugeumui seongmul - 2bu', '(2011)', '8.1'],
 ['비포 선라이즈', '(1995)', '8.1'],
 ['12 Years a Slave', '(2013)', '8.1'],
 ['Ben-Hur', '(1959)', '8.1'],
 ['The Grand Budapest Hotel', '(2014)', '8.1'],
 ['On the Waterfront', '(1954)', '8.1'],
 ['Gone Girl', '(2014)', '8.1'],
 ['Smultronstället', '(1957)', '8.1'],
 ['The General', '(1926)', '8.1'],
 ['Barry Lyndon', '(1975)', '8.1'],
 ['In the Name of the Father', '(1993)', '8.1'],
 ['The Deer Hunter', '(1978)', '8.1'],
 ['The Third Man', '(1949)', '8.1'],
 ['핵소 고지', '(2016)', '8.1'],
 ['Le salaire de la peur', '(1953)', '8.1'],
 ['Salinui chueok', '(2003)', '8.1'],
 ['Waildeu Teiljeu: Cham-eul Su Eobsneun Sungan', '(2014)', '8.1'],
 ['Sherlock Jr.', '(1924)', '8.1'],
 ['Mr. Smith Goes to Washington', '(1939)', '8.1'],
 ['매드맥스: 분노의 도로', '(2015)', '8.1'],
 ['Mary and Max', '(2009)', '8.1'],
 ['The Seventh Seal', '(1957)', '8.1'],
 ['드래곤 길들이기', '(2010)', '8.1'],
 ['Monsters, Inc.', '(2001)', '8.1'],
 ['죽은 시인의 사회', '(1989)', '8.1'],
 ['죠스', '(1975)', '8.1'],
 ['Room', '(2015)', '8.1'],
 ['위대한 레보스키', '(1998)', '8.1'],
 ['동경 이야기', '(1953)', '8.1'],
 ["La passion de Jeanne d'Arc", '(1928)', '8.1'],
 ['Ford v Ferrari', '(2019)', '8.1'],
 ['Hotel Rwanda', '(2004)', '8.0'],
 ['록키', '(1976)', '8.0'],
 ['Platoon', '(1986)', '8.0'],
 ['라따뚜이', '(2007)', '8.0'],
 ['스포트라이트', '(2015)', '8.0'],
 ['로건', '(2017)', '8.0'],
 ['터미네이터', '(1984)', '8.0'],
 ['Stand by Me', '(1986)', '8.0'],
 ['Rush', '(2013)', '8.0'],
 ['Network', '(1976)', '8.0'],
 ['Before Sunset', '(2004)', '8.0'],
 ['Into the Wild', '(2007)', '8.0'],
 ['오즈의 마법사', '(1939)', '8.0'],
 ['The Best Years of Our Lives', '(1946)', '8.0'],
 ['엑소시스트: 디렉터스 컷', '(1973)', '8.0'],
 ['사랑의 블랙홀', '(1993)', '8.0'],
 ['The Incredibles', '(2004)', '8.0'],
 ['To Be or Not to Be', '(1942)', '8.0'],
 ['La haine', '(1995)', '8.0'],
 ['캐리비안의 해적: 블랙펄의 저주', '(2003)', '8.0'],
 ['Pather Panchali', '(1955)', '8.0'],
 ['La battaglia di Algeri', '(1966)', '8.0'],
 ["Hachi: A Dog's Tale", '(2009)', '8.0'],
 ['The Grapes of Wrath', '(1940)', '8.0'],
 ['Jai Bhim', '(2021)', '8.0'],
 ['Babam ve Oglum', '(2005)', '8.0'],
 ['Amores perros', '(2000)', '8.0'],
 ['Rebecca', '(1940)', '8.0'],
 ['Ahgassi', '(2016)', '8.0'],
 ['Cool Hand Luke', '(1967)', '8.0'],
 ['사운드 오브 뮤직', '(1965)', '8.0'],
 ['The 400 Blows', '(1959)', '8.0'],
 ['어느 날 밤에 생긴 일', '(1934)', '8.0'],
 ['Persona', '(1966)', '8.0'],
 ['Life of Brian', '(1979)', '8.0'],
 ['The Iron Giant', '(1999)', '8.0'],
 ['헬프', '(2011)', '8.0'],
 ['알라딘', '(1992)', '8.0'],
 ['데르수 우잘라', '(1975)', '8.0'],
 ['Dances with Wolves', '(1990)', '8.0']]

## No. 2 (2점)
### 수집한 정보들을 데이터프레임 형태로 변환하세요.
### 해당 데이터프레임에는 순위('Rank'), 제목('Title'), 연도('Year'), 평점('Rate') 열이 존재해야 합니다.
### 특히 'Rank'와 'Year'는 int, 'Rate'는 float 자료형으로 변환하세요.

In [5]:
df = pd.DataFrame(result) # dataframe으로 변경

In [6]:
df['rank'] = range(1,251) # 순위는 해당 내용에서 가지고 오지 않았지만 순서대로 되어있으니, range만들어 df에 할당

In [7]:
df.columns = ['title','year','rate','rank'] # 컬럼명 지정

In [8]:
for i in range(len(df)):
    df.year[i] = df.year[i].replace('(','').replace(')','') # year에 괄호가 포함되어 있어 제거 후 astype로 타입 변경

C:\Users\user\AppData\Local\Temp\ipykernel_7684\441916821.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.year[i] = df.year[i].replace('(','').replace(')','')

In [9]:
df['rank'] = df['rank'].astype('int')
df['year'] = df['year'].astype('int')
df['rate'] = df['rate'].astype('float')
# 각 컬럼명 지정 / dict 형태로도 변경 가능

In [11]:
df = df[['rank','title','year','rate']] # 보기 편하게 rank, title, year, rate순으로 df 변경

In [12]:
df # 최종 확인

     rank                  title  year  rate
0       1                 쇼생크 탈출  1994   9.2
1       2                 Daeboo  1972   9.2
2       3                 다크 나이트  2008   9.0
3       4  The Godfather Part II  1974   9.0
4       5            12명의 성난 사람들  1957   9.0
..    ...                    ...   ...   ...
245   246         The Iron Giant  1999   8.0
246   247                     헬프  2011   8.0
247   248                    알라딘  1992   8.0
248   249                데르수 우잘라  1975   8.0
249   250     Dances with Wolves  1990   8.0

[250 rows x 4 columns]

## No. 3 (2점)
### 해당 데이터를 10년 단위로 정리하겠습니다.
### 데이터가 1920년대부터 존재하므로, 1920년대부터 2020년대까지 총 11개로 나눌 수 있습니다.
### Top 250을 대상으로, 시대별로 (1) Top 250에 포함된 영화 수, (2) 평균 평점, (3) 최고 평점 영화를 출력하세요.
### 최고 평점 영화는 시대별로 가장 순위가 높은 영화를 출력하시면 됩니다.
##### ex) 출력 결과:
##### 1920년대 - 영화 수: 6 / 평균 평점: 8.13 / 최고 평점 영화: Metropolis
##### 1930년대 - 영화 수: 7 / 평균 평점: 8.17 / 최고 평점 영화: 모던 타임즈
##### .....
##### 2020년대 - 영화 수: 6 / 평균 평점: 8.13 / 최고 평점 영화: Hamilton

In [13]:
df2 = df.copy() # 첫번쨰 df 복사

In [14]:
df2['year_10'] = df['year']//10 * 10 # 년대로 변경하기 위해 10의 몫에 10을 다시 곱해 변경

In [15]:
df2 # year_10 변수 확인

     rank                  title  year  rate  year_10
0       1                 쇼생크 탈출  1994   9.2     1990
1       2                 Daeboo  1972   9.2     1970
2       3                 다크 나이트  2008   9.0     2000
3       4  The Godfather Part II  1974   9.0     1970
4       5            12명의 성난 사람들  1957   9.0     1950
..    ...                    ...   ...   ...      ...
245   246         The Iron Giant  1999   8.0     1990
246   247                     헬프  2011   8.0     2010
247   248                    알라딘  1992   8.0     1990
248   249                데르수 우잘라  1975   8.0     1970
249   250     Dances with Wolves  1990   8.0     1990

[250 rows x 5 columns]

In [16]:
result_total = []
for decade, group in df2.groupby('year_10'): # groupby로 시대별로 묶어 진행
    count = len(group) # 해당 그룹 몇개인지 확인 = 영화 수에 해당
    mean_rating = group['rate'].mean() # 평균 개산 = 평균 평점에 해당
    max_rating = group.loc[group['rate'].idxmax(), 'title'] # 그룹내 최고 평점 확인 = 최고 평점 영화에 해당
    result_total.append(f"{decade} - 영화 수: {count} / 평균 평점: {mean_rating:.2f} / 최고 평점 영화: {max_rating}") # 해당 내용 묶어 list에 추가

# 결과 출력
for line in result_total:
    print(line)

1920 - 영화 수: 6 / 평균 평점: 8.13 / 최고 평점 영화: Metropolis
1930 - 영화 수: 7 / 평균 평점: 8.17 / 최고 평점 영화: 모던 타임즈
1940 - 영화 수: 12 / 평균 평점: 8.19 / 최고 평점 영화: 멋진 인생
1950 - 영화 수: 23 / 평균 평점: 8.23 / 최고 평점 영화: 12명의 성난 사람들
1960 - 영화 수: 18 / 평균 평점: 8.24 / 최고 평점 영화: 석양의 무법자
1970 - 영화 수: 19 / 평균 평점: 8.27 / 최고 평점 영화: Daeboo
1980 - 영화 수: 26 / 평균 평점: 8.24 / 최고 평점 영화: 스타워즈 에피소드 5 - 제국의 역습
1990 - 영화 수: 42 / 평균 평점: 8.36 / 최고 평점 영화: 쇼생크 탈출
2000 - 영화 수: 48 / 평균 평점: 8.25 / 최고 평점 영화: 다크 나이트
2010 - 영화 수: 43 / 평균 평점: 8.21 / 최고 평점 영화: 인셉션
2020 - 영화 수: 6 / 평균 평점: 8.13 / 최고 평점 영화: Hamilton